version: "3.7"

services:
    migrations:
        build: ./flaskapp
        container_name: migrations
        environment:
            - FLASK_ENV=production
            - FLASK_APP=run.py
            - MYSQL_USER
            - MYSQL_PASSWORD
            - MYSQL_HOST
            - MYSQL_PORT
            - MYSQL_DATABASE
        command: flask db upgrade

    flask:
        build: ./flaskapp
        container_name: flask
        restart: always
        environment:
            - FLASK_ENV=production
            - FLASK_APP=run.py
            - SECRET_KEY
            - SLACK_API_TOKEN
            - MYSQL_USER
            - MYSQL_PASSWORD
            - MYSQL_HOST
            - MYSQL_PORT
            - MYSQL_DATABASE
        expose:
            - 8080

    nginx:
        build: ./nginx
        container_name: nginx
        restart: always
        ports:
            - "3050:80"
        depends_on:
            - flask