version: '3.7'

services:
    broker-rabbitmq:
        image: "rabbitmq:3.7.14-management"
        environment:
            - RABBITMQ_DEFAULT_USER=client
            - RABBITMQ_DEFAULT_PASS=client
    db:
        image: 'mysql:5.7.28'
        environment:
            MYSQL_HOST: 'localhost'
            MYSQL_DATABASE: 'wallet_sentinel_dev'
            # So you don't have to use root, but you can if you like
            MYSQL_USER: 'admin'
            # You can use whatever password you like
            MYSQL_PASSWORD: 'adminpassword'
            # Password for root access
            MYSQL_ROOT_PASSWORD: 'rootpassword'
        ports:
            # <Port exposed> : < MySQL Port running inside container>
            - '3308:3306'
        expose:
            # Opens port 3306 on the container
            - '3306'
    
    # db-viewer:
    #     image: phpmyadmin/phpmyadmin:4.9
    #     container_name: phpmyadmin
    #     environment:
    #         - PMA_ARBITRARY=1
    #     restart: always
    #     ports:
    #      - 8080:80
    #     volumes:
    #      - /sessions

    migrations:
        build: .
        environment:
            - APP_ENV=${APP_ENV}
        command: flask db upgrade
        depends_on:
            - db

    flask:
        build: .
        restart: always
        ports:
            - "5000:5000"
        environment:
            - APP_ENV=${APP_ENV}
        depends_on:
            - broker-rabbitmq
            - db
            - migrations
    
    flask-worker:
        build: .
        command: celery worker --workdir=. -A tasks.celery --loglevel=info
        environment:
          - APP_ENV=${APP_ENV}
        depends_on:
          - broker-rabbitmq
          - db
          - migrations

    flask-beat:
        build: .
        command: celery beat -A tasks.celery --loglevel=info
        environment:
          - APP_ENV=${APP_ENV}
        depends_on:
          - broker-rabbitmq
          - db
          - migrations